spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test3
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      #      show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
logging.level:
  org.hibernate.SQL: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"