spring:
  #datasource:
   # url: jdbc:h2:tcp://localhost/~/test3
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mariadb://localhost:3306/newdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1225
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      #      show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging.level:
  org.hibernate.SQL: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
